### ISSUE TITLE
Add .NET Standard 2.0 compatible worker as option to dotnet-isolated entry

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-tooling-feed#330] opened 2022-03-18 19:58 UTC
The tooling feed will need to expose a new isolated worker which is built against .NET Standard 2.0. This should not initially be a public feed entry - validation will be needed against it.

New templates to be created which would be a part of that: https://github.com/Azure/azure-functions-templates/issues/1186

Per tooling partner discussion, v4 runtime variant needs to call this out with a new required capability. A proposal might be "netfx-isolated" or similar (v1 used the string "netframework" it looks like). As long as it's a new key, that should be fine. To keep things reasonably consisting, it is probably worth keeping the "-isolated" suffix on it. Overall, we need some discussion for the specific entry's title.

**Comment by fabiocav** [comment] 2022-06-29 20:58
This work is already in progress and @liliankasem is driving the changes.

Flagging here as we should be able to close this once the latest PRs are merged.

**Comment by fabiocav** [comment] 2022-06-29 20:59
Closing as duplicate of: https://github.com/Azure/azure-functions-tooling-feed/issues/357

**Closed by fabiocav** 2022-06-29 20:59 UTC
